Added screencasts of Porphyry features
Hypertopic/Hypertopic.github.io pull request #1
Opened 2021-01-26 14:02 UTC by jejroux

2021-01-27 08:55 UTC, benel commented
Merci @jejroux.
Et leur intégration dans le texte ?

2021-01-27 09:43 UTC, jejroux commented
J'avais prévu des les ajouter dans une autre pull request.

2021-01-27 09:46 UTC, benel commented
C'est un livrable... autant avoir quelque chose de complet.

2021-01-27 09:50 UTC, jejroux commented
En effet... J'ai ajouté le commit à cette pull request.

2021-01-27 13:40 UTC, jejroux commented
@benel Y a-t-il d'autres modifications à apporter ?

2021-01-29 09:04 UTC, benel requested changes
C'est très bien !

Il faudrait juste corriger (en plus de la petite coquille dans le texte) "category" en "topic" dans le nom d'un des fichiers.

2021-01-29 09:04 UTC, benel commented on porphyry.md
> +  <figcaption> Dans le portfolio VITRAUX, consultation des vitraux (items) correspondant à la période arts-déco.</figcaption>
Ça s'écrit tout simplement "Art déco". https://fr.wikipedia.org/wiki/Art_déco

2021-01-29 11:32 UTC, jejroux commented
Je pense avoir tout corrigé. La pull request n'est pas vraiment très "propre", si vous voulez que je la refasse pour qu'elle soit plus compréhensible je peux le faire.

2021-01-29 13:17 UTC, benel commented
Comme vous le voyez dans l'historique, je suis moins "à cheval" pour celui du site que pour celui des logiciels.
Mais en même temps c'est vrai que ce n'est pas très propre ;)
Si vous pouvez réécrire l'historique, c'est mieux (par contre vous allez un peu "galèrer" car vous êtes sur votre branche maître).

2021-02-01 08:40 UTC, jejroux commented
Désolé mais en effet je galère, je ne sais pas comment réécrire l'historique et je préfère ne pas faire de bêtise...

2021-02-10 16:11 UTC, merged